---
# This playbook sets up basic splunk security 
- name: copy splunk passwd file
  tags:
   - install
   - security
  copy: 
    src: "splunk_creds/{{splunkforwader_passwd}}" 
    dest: "{{ splunkforwarder_path }}/etc" 
    owner: "{{ splunkforwarder_system_user }}" 
    group: "{{ splunkforwarder_system_user }}" 
    mode: 700
  notify: restart splunk
  when: false # disable for now

- name: create certs folder
  tags:
   - install
   - security
  file: 
    path: "{{ splunkforwarder_path }}/certs" 
    owner: "{{ splunkforwarder_system_user }}" 
    group: "{{ splunkforwarder_system_user }}" 
    mode: 700 
    state: directory
  notify: restart splunk
  when: false # disable for now
